In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
!ls data

OEM_Emergency_Notifications.csv   tweets_pseg_dec13_sep20.csv
OEM_Non_Outages.csv               tweets_pseg_jun27_apr06.csv
final_df.csv                      tweets_pseg_sep6_july2
nlp_tweets.csv                    tweets_scrape_first_df.csv
nlp_tweets_2012_2017.csv          weather_outage_merge.csv
non_outages.csv                   weather_target_drop_merged.csv
open_nyc.csv                      weather_target_merged.csv
target.csv                        weather_target_numerical.csv
tweets.csv                        weather_target_numerical_drop.csv
tweets_2.csv                      working_df.csv
tweets_3.csv

In [3]:
tweets = pd.read_csv('./data/nlp_tweets_2012_2017.csv')
tweets['datetime'] = pd.to_datetime(tweets['datetime'])
tweets.shape

(2082, 19)

In [10]:
tweets.columns

Index(['index', 'ID', 'datetime', 'has_media', 'is_reply', 'is_retweet',
       'medias', 'nbr_favorite', 'nbr_reply', 'nbr_retweet', 'text', 'url',
       'user_id', 'usernameTweet', 'regex_clean_tweets', 'lemmed_tweet',
       'nouns', 'proper_nouns', 'geopolitical_ents'],
      dtype='object')

In [13]:
tweets_datetime = tweets[['datetime', 'text', 'regex_clean_tweets', 'lemmed_tweet']]

In [14]:
tweets_datetime.head(2)

,datetime,text,regex_clean_tweets,lemmed_tweet
0,2012-10-01 00:00:00,@ ckundo Inspired by your ConEd summary ou...,ckundo Inspired ConEd summary outage info Ruby...,ckundo Inspired ConEd summary outage info Ruby...
1,2012-10-06 13:00:00,Partial power outage at #MediaLoft That's...,Partial power outage MediaLoft That twice week...,Partial power outage MediaLoft That twice week...

In [4]:
weather = pd.read_csv('./data/weather_outage_merge.csv')
weather['datetime'] = pd.to_datetime(weather['datetime'])
weather.shape

(44460, 41)

In [5]:
weather.head(2)

,datetime,temperature_f,wind_dir_degrees,wind_speed_mph,broken_clouds,drizzle,dust,few_clouds,fog,freezing_rain,...,smoke,snow,squalls,thunderstorm,thunderstorm_with_heavy_rain,thunderstorm_with_light_drizzle,thunderstorm_with_light_rain,thunderstorm_with_rain,very_heavy_rain,outage
0,2012-10-01 13:00:00,59.11,260.0,15,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0.0
1,2012-10-01 14:00:00,59.16,260.0,15,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0.0

In [30]:
temp = pd.merge(left=tweets_datetime,
         right=weather,
         how='right',
         on='datetime')

In [31]:
sorted(temp.isnull().sum(), reverse=True)
temp.isnull().sum().sort_values(ascending=False)

text                                   43464
regex_clean_tweets                     43464
lemmed_tweet                           43464
outage                                     0
freezing_rain                              0
light_intensity_shower_rain                0
light_intensity_drizzle                    0
heavy_thunderstorm                         0
heavy_snow                                 0
heavy_intensity_rain                       0
heavy_intensity_drizzle                    0
haze                                       0
few_clouds                                 0
fog                                        0
very_heavy_rain                            0
dust                                       0
drizzle                                    0
broken_clouds                              0
wind_speed_mph                             0
wind_dir_degrees                           0
temperature_f                              0
light_rain                                 0
light_rain_and_snow                        0
light_snow                                 0
sky_is_clear                               0
thunderstorm_with_rain                     0
thunderstorm_with_light_rain               0
thunderstorm_with_light_drizzle            0
thunderstorm_with_heavy_rain               0
thunderstorm                               0
squalls                                    0
snow                                       0
smoke                                      0
shower_rain                                0
mist                                       0
scattered_clouds                           0
sand/dust_whirls                           0
sand                                       0
proximity_thunderstorm_with_rain           0
proximity_thunderstorm_with_drizzle        0
proximity_thunderstorm                     0
overcast_clouds                            0
moderate_rain                              0
datetime                                   0
dtype: int64

In [32]:
temp.head()

,datetime,text,regex_clean_tweets,lemmed_tweet,temperature_f,wind_dir_degrees,wind_speed_mph,broken_clouds,drizzle,dust,...,smoke,snow,squalls,thunderstorm,thunderstorm_with_heavy_rain,thunderstorm_with_light_drizzle,thunderstorm_with_light_rain,thunderstorm_with_rain,very_heavy_rain,outage
0,2012-10-06 13:00:00,Partial power outage at #MediaLoft That's...,Partial power outage MediaLoft That twice week...,Partial power outage MediaLoft That twice week...,61.55,56.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
1,2012-10-12 01:00:00,"Um, can someone call ConEd , there's a power...",Um someone call ConEd power outage Bronx Sourc...,Um someone call ConEd power outage Bronx Sourc...,59.48,260.0,15,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2,2012-10-20 23:00:00,Power outage took over my entire block as s...,Power outage took entire block soon loaded Con...,Power outage took entire block soon loaded Con...,65.86,170.0,11,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
3,2012-10-26 15:00:00,Mayor: A major concern given this type of stor...,Mayor A major concern given type storm possibi...,Mayor A major concern given type storm possibi...,59.88,40.0,6,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
4,2012-10-26 15:00:00,A major concern given this storm is the possib...,A major concern given storm possibility prolon...,A major concern given storm possibility prolon...,59.88,40.0,6,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0

In [33]:
temp.shape

(45545, 44)

In [35]:
temp.fillna(value = 'hello').tail()

,datetime,text,regex_clean_tweets,lemmed_tweet,temperature_f,wind_dir_degrees,wind_speed_mph,broken_clouds,drizzle,dust,...,smoke,snow,squalls,thunderstorm,thunderstorm_with_heavy_rain,thunderstorm_with_light_drizzle,thunderstorm_with_light_rain,thunderstorm_with_rain,very_heavy_rain,outage
45540,2017-10-27 20:00:00,hello,hello,hello,62.27,0.0,6,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
45541,2017-10-27 21:00:00,hello,hello,hello,61.37,0.0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
45542,2017-10-27 22:00:00,hello,hello,hello,58.57,196.0,4,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
45543,2017-10-27 23:00:00,hello,hello,hello,54.80,171.0,6,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
45544,2017-10-28 00:00:00,hello,hello,hello,53.27,0.0,4,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0

In [36]:
final_df = temp.fillna(value = 'hello')
final_df.shape

(45545, 44)

In [37]:
final_df.to_csv('./data/final_df_full.csv')

In [28]:
!ls data

OEM_Emergency_Notifications.csv   tweets_3.csv
OEM_Non_Outages.csv               tweets_pseg_dec13_sep20.csv
final_df.csv                      tweets_pseg_jun27_apr06.csv
final_df_full.csv                 tweets_pseg_sep6_july2
nlp_tweets.csv                    tweets_scrape_first_df.csv
nlp_tweets_2012_2017.csv          weather_outage_merge.csv
non_outages.csv                   weather_target_drop_merged.csv
open_nyc.csv                      weather_target_merged.csv
target.csv                        weather_target_numerical.csv
tweets.csv                        weather_target_numerical_drop.csv
tweets_2.csv                      working_df.csv